-- Sample vector data for initial setup
-- This is a minimal data.sql file for Spring Boot's database initialization
-- The vector store will be populated programmatically when the application runs

-- Insert a single sample record to ensure the database initializer has valid SQL to execute
-- Create a vector with 1536 dimensions filled with zeros (except first few values)
INSERT INTO vector_store (content, metadata, embedding) 
VALUES (
  'Spring AI sample content', 
  '{"source": "initial_data", "type": "example"}', 
  -- Create a zero-filled array of 1536 dimensions, then set the first few values
  array_replace(array_fill(0::float4, ARRAY[1536]), 1, 0.1)::vector
);

-- You can add more INSERT statements here if needed

-- Note: Actual vector embeddings will be generated by the Azure OpenAI service
-- This file exists to satisfy the Spring Boot requirement 